### ISSUE TITLE
Notifications from Intercom in Front are nonsensical.

### ISSUE THREAD

**Issue by areskub** [frontapp/front-intercom#1]
Seems that if you reply to a message in Intercom, Front gives you a notification but the names in the notification are all “Intercom”.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/L2luYm94ZXMvdG9waWNzLzMwNjE=)

**Comment by eramdam** [comment]
Closing this in favor of https://github.com/frontapp/front/issues/1108
